### ISSUE TITLE
Web UI has crashed

### ISSUE THREAD

**Issue by gmipf** [maksis/airdcpp-webclient#412]
Web UI has crashed

Please submit a bug report with the requested information (and the crash details below) at the issue tracker.
Crash details

i@https://[AddressRemoved]/js/424.b407aaf3218fa480b144.chunk.js:1:8331
oa@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2258689
Rs@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2310894
kA@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2298103
BA@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2298031
vA@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2297892
fA@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2294879
Gn/<@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2244587
60053/t.unstable_runWithPriority@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2665854
Yn@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2244364
Gn@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2244534
Wn@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2244467
AA@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2292258
enqueueForceUpdate@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2248722
72408/p.prototype.forceUpdate@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2640915
Q/this.dataLoader<@https://[AddressRemoved]/js/424.b407aaf3218fa480b144.chunk.js:1:21328
onItemsUpdated@https://[AddressRemoved]/js/424.b407aaf3218fa480b144.chunk.js:1:20316
i@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2648897
80179/n.prototype.emit@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2658731
68656/t.trigger@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2649188
_handleUpdate@https://[AddressRemoved]/js/424.b407aaf3218fa480b144.chunk.js:1:25621
17187/r.prototype.emit@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:1713151
handleMessage@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2926241
S@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2930362

### Current UI and client versions:

Copy from *Settings* -> *About*

Application version
AirDC++w 2.11.2 x86_64
Web UI version
2.11.2

Firefox 93.0 (64-Bit)

### Operating system:

Kubuntu 20.04 5.13.0-1014-oem

**Comment by maksis** [comment]
These all seem to be related to list views.... maybe it's finally time to rework the way how table data is managed

```
i@https://[AddressRemoved]/js/424.b407aaf3218fa480b144.chunk.js:1:8331
    at className (webpack://airdcpp-webui/src/components/format/FormattedIp.tsx:15:7)
```

```
filter@https://domain.tld:11223/js/queue.0e532f2a56e464d1626b.chunk.js:1:3614
    at bundle (webpack://airdcpp-webui/src/actions/ui/QueueBundleActions.ts:16:48)
    at  (webpack://airdcpp-webui/src/routes/Queue/components/BundleFileDialog.tsx:51:15)
```


```
Re/this.isActive@https://host:port/js/queue.0e532f2a56e464d1626b.chunk.js:1:12665
    at rowData (webpack://airdcpp-webui/src/routes/Queue/components/Queue.tsx:51:12)
    at Queue (webpack://airdcpp-webui/src/routes/Queue/components/Queue.tsx:202:33)
```

**Comment by peps1** [comment]
Thanks @maksis, so should we better post what page was open during the issue?

In this case it was the /transfers page.


```
Re/this.isActive@https://host:port/js/queue.0e532f2a56e464d1626b.chunk.js:1:12665
render@https://host:port/js/424.83f0cedf9d07b9d54fcb.chunk.js:1:15322
Ra@https://host:port/js/main.c01c26460331633a96e2.entry.js:2:2271785
Pa@https://host:port/js/main.c01c26460331633a96e2.entry.js:2:2271584
Rs@https://host:port/js/main.c01c26460331633a96e2.entry.js:2:2312499
kA@https://host:port/js/main.c01c26460331633a96e2.entry.js:2:2298652
BA@https://host:port/js/main.c01c26460331633a96e2.entry.js:2:2298580
vA@https://host:port/js/main.c01c26460331633a96e2.entry.js:2:2298441
fA@https://host:port/js/main.c01c26460331633a96e2.entry.js:2:2295428
Gn/<@https://host:port/js/main.c01c26460331633a96e2.entry.js:2:2245136
60053/t.unstable_runWithPriority@https://host:port/js/main.c01c26460331633a96e2.entry.js:2:2666240
Yn@https://host:port/js/main.c01c26460331633a96e2.entry.js:2:2244913
Gn@https://host:port/js/main.c01c26460331633a96e2.entry.js:2:2245083
Wn@https://host:port/js/main.c01c26460331633a96e2.entry.js:2:2245016
AA@https://host:port/js/main.c01c26460331633a96e2.entry.js:2:2292807
enqueueSetState@https://host:port/js/main.c01c26460331633a96e2.entry.js:2:2248990
72408/p.prototype.setState@https://host:port/js/main.c01c26460331633a96e2.entry.js:2:2641214
s/t.measure/t._animationFrameID<@https://host:port/js/main.c01c26460331633a96e2.entry.js:2:2552966
```

### Current UI and client versions

Application version: AirDC++w 2.11.2b-66-g519b x86_64
Web UI version: 2.11.2-beta.2

Firefox Developer Edition 95.0b3 (64-bit)
### Operating system

Browser: Windows 11
AirDC: Ubuntu 20.04.3 LTS

**Comment by maksis** [comment]
Well... that's definitely interesting as the first line in your stacktrace refers to the queue view

**Comment by peps1** [comment]
yeah that's weird, the url said /transfers, but i don't remember if that's where i left it. I'll keep a closer eye on that.

**Comment by maksis** [comment]
This could also be related to https://github.com/airdcpp-web/airdcpp-webclient/issues/386 (maybe the latest versions of Firefox have similar throttling?)

**Comment by gmipf** [comment]
Here again:

Web UI has crashed

Please submit a bug report with the requested information (and the crash details below) at the issue tracker.
Crash details

G@https://[AddressRemoved]/js/transfers.5a7661c5701a462d4c53.chunk.js:1:7540
oa@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2258689
Rs@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2310894
kA@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2298103
BA@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2298031
vA@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2297892
fA@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2294879
64448/Gn/<@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2244587
60053/t.unstable_runWithPriority@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2665854
Yn@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2244364
Gn@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2244534
Wn@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2244467
AA@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2292258
enqueueForceUpdate@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2248722
72408/p.prototype.forceUpdate@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2640915
78230/Q/this.dataLoader<@https://[AddressRemoved]/js/424.b407aaf3218fa480b144.chunk.js:1:21328
onItemsUpdated@https://[AddressRemoved]/js/424.b407aaf3218fa480b144.chunk.js:1:20316
i@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2648897
80179/n.prototype.emit@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2658731
68656/t.trigger@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2649188
_handleUpdate@https://[AddressRemoved]/js/424.b407aaf3218fa480b144.chunk.js:1:25621
17187/r.prototype.emit@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:1713151
handleMessage@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2926241
S@https://[AddressRemoved]/js/main.d64158ea2453985dde98.entry.js:2:2930362



Web UI version: 2.11.2
OS: Fedora 36
Browser: 104.0.2

**Comment by gmipf** [comment]
```
Web UI has crashed

Please submit a bug report with the requested information (and the crash details below) at the issue tracker.
Crash details

a@https://[ip:port]/js/424.b9b775d50fbed2ec85ca.chunk.js:1:9193
ka@https://[ip:port]/js/main.560335911ba879ef8877.entry.js:2:2338934
ks@https://[ip:port]/js/main.560335911ba879ef8877.entry.js:2:2395766
vu@https://[ip:port]/js/main.560335911ba879ef8877.entry.js:2:2384920
Cu@https://[ip:port]/js/main.560335911ba879ef8877.entry.js:2:2384848
gu@https://[ip:port]/js/main.560335911ba879ef8877.entry.js:2:2384709
uu@https://[ip:port]/js/main.560335911ba879ef8877.entry.js:2:2381852
Yn@https://[ip:port]/js/main.560335911ba879ef8877.entry.js:2:2322780
ou@https://[ip:port]/js/main.560335911ba879ef8877.entry.js:2:2378950
enqueueForceUpdate@https://[ip:port]/js/main.560335911ba879ef8877.entry.js:2:2330086
72408/g.prototype.forceUpdate@https://[ip:port]/js/main.560335911ba879ef8877.entry.js:2:2520603
78230/Q/this.dataLoader<@https://[ip:port]/js/424.b9b775d50fbed2ec85ca.chunk.js:1:22048
onItemsUpdated@https://[ip:port]/js/424.b9b775d50fbed2ec85ca.chunk.js:1:21038
i@https://[ip:port]/js/main.560335911ba879ef8877.entry.js:2:2529402
80179/n.prototype.emit@https://[ip:port]/js/main.560335911ba879ef8877.entry.js:2:2539219
68656/t.trigger@https://[ip:port]/js/main.560335911ba879ef8877.entry.js:2:2529693
_handleUpdate@https://[ip:port]/js/424.b9b775d50fbed2ec85ca.chunk.js:1:26362
17187/r.prototype.emit@https://[ip:port]/js/main.560335911ba879ef8877.entry.js:2:1786903
handleMessage@https://[ip:port]/js/main.560335911ba879ef8877.entry.js:2:2760414
I@https://[ip:port]/js/main.560335911ba879ef8877.entry.js:2:2764522
```

Web UI version: 2.12.0
OS: Fedora 38
Browser: Firefox 119.0 (64-Bit)
